### PR TITLE
Fixed missing printing

### PR DESCRIPTION
**Pull request by ilvacca**
The "reload(sys)" line was causing error for printing commands.

### CODE REVIEW

**Comment by mclmza** [comment]
What error?

**Comment by ilvacca** [comment]
Ciao Michele, mi sa che possiamo parlare italiano.

Usando il tuo utilissimo scraper mi sono accorto che il log non funzionava. Non usciva fuori alcun print. Ho visto che il problema era causato dal “reload(sys)” quindi ho trovato una soluzione e ho fatto il pull.

Alessio Vaccaro

________________________________
Da: Michele Mazza <notifications@github.com>
Inviato: Monday, June 25, 2018 11:04:40 AM
A: mclmza/linkedin-learning-downloader
Cc: Alessio Vaccaro; Author
Oggetto: Re: [mclmza/linkedin-learning-downloader] Fixed missing printing (#82)


What error?

**Comment by vishal4003** [comment]
**PS C:\linkedin> python lld.py
Traceback (most recent call last):
  File "lld.py", line 13, in <module>
    reload(sys)
NameError: name 'reload' is not defined
PS C:\linkedin>**

This is the error showing.
sketch git

**Comment by vishal4003** [comment]
please update the llb.py file

**Comment by ilvacca** [comment]
The error is not this one.
The code gives no error, simply it doesn't print anything when launched.
The scraper works perfectly but I have no "infos" about the download state.

EDIT: Ok, I found. Your script works perfectly in "cmd" but not in the Python IDLE.  No corrections to make.
Sorry for the time spent with my request. You can close it.

Best regards,
Alessio Vaccaro


________________________________
Da: vishal4003 <notifications@github.com>
Inviato: mercoledì 27 giugno 2018 10:52
A: mclmza/linkedin-learning-downloader
Cc: Alessio Vaccaro; Author
Oggetto: Re: [mclmza/linkedin-learning-downloader] Fixed missing printing (#82)


PS C:\linkedin> python lld.py
Traceback (most recent call last):
File "lld.py", line 13, in
reload(sys)
NameError: name 'reload' is not defined
PS C:\linkedin>

This is the error showing.
[sketch git]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F16304084%2F41963497-6011a4a2-7a15-11e8-8eac-b485405e8863.png&data=02%7C01%7C%7Caa1d9e62cb5c4bf64c7408d5dc0b42b4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636656863269201651&sdata=g%2BrvIN3RmpvcHXh%2FlPSYQJEyGEsb%2Fy1XuexzYvhs5A4%3D&reserved=0>

**Comment by vishal4003** [comment]
@ilvacca the updated file you have provided too didn,t work on windows Powrshell. Please check it running in your system or not. i have attached my issue as shown above.

**Comment by ilvacca** [comment]
Ok ok, you can discard it.

Thank you.

-------- Messaggio originale --------
Oggetto: Re: [mclmza/linkedin-learning-downloader] Fixed missing printing (#82)
Da: vishal4003
A: mclmza/linkedin-learning-downloader
CC: Alessio Vaccaro ,Mention


@ilvacca<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Filvacca&data=02%7C01%7C%7C7b5635e177d246f13eb308d5dc24adba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636656972441471770&sdata=S%2FTORoUd4V0wRUjjZu%2F3dWMrRS0Hgbge4Z1EUfVG768%3D&reserved=0> the updated file you have provided too didn,t work on windows Powrshell. Please check it running in your system or not. i have attached my issue as shown above.

**Pull request closed without merging**
